### ISSUE TITLE
QA Feedback: Bugs

### ISSUE THREAD

**Issue by jojobyte** [dashhive/dashchum#1]
Some bugs caught while QA Testing by Spencer

- [x] `dashmate setup local` and `dashmate group start` **BOTH** had to be run multiple times
- [x] the wrong buttons show when there is a zero balance
- [x] when you push generate identity it [object Object]'s below
  - [x] and stored [object Object] in local storage
- [x] Generate Contract: nothing on screen changed after update but the local storage changed

**Comment by jojobyte** [comment]
These issues should be resolved.

**Comment by kodetronik** [comment]
-thanks!
