### ISSUE TITLE
QA Feedback: Enhancements

### ISSUE THREAD

**Issue by jojobyte** [dashhive/dashchum#2]
Some feedback generated while QA Testing by Spencer

- [x] Clarify Configuration stage
- [x] Clarify Usage
- [x] Clarify what Dash Chum does and what you should expect to see in browser
- [x] Add reference to stopping `dashmate group stop`

**Comment by jojobyte** [comment]
These issues should be resolved.

**Comment by kodetronik** [comment]
thanks!
